   try{
window.aax = window.aax|| {};
window.aax.isLoaded = true;
var aaxSettings = {"srvd":"https:\/\/c.aaxads.com","pub":"AAXV53D7Q","pid":"8PR6YK195","itype":"AAX","gpvid":"332","gexid":"2","gdpr":"1","gdprconsent":"0","uspst":"0","uspcn":"","icr":"0","feedbackConfig":{"adIcon":{"providers":[-1],"enabled":false},"adIconConfig":{"54":{"id":"54","text":"AD","css":"background-color: #8B8B8B; color: #009821;"},"79":{"id":"79","text":"AD","css":"background-color: #8B8B8B; color: #CC6200;"},"97":{"id":"97","text":"AD","css":"background-color: #8B8B8B; color: #0071BC;"},"159":{"id":"310","text":"AD","css":"background-color: #ffffff; color: #ef36be; border-color: #ef36be;"},"195":{"id":"195","text":"Ad","css":"background-color: #ffffff; color: #B250FF; border-color: #B250FF;"},"203":{"id":"203","text":"AD","css":"background-color: #8B8B8B; color: #000000;"},"206":{"id":"206","text":"ad","css":"background-color: #ffffff; color: #000000; border-color: #a1a1a1;"},"209":{"id":"209","text":"AD","css":"background-color: #ffffff; color: #0071bc; border-color: #ffffff;"},"212":{"id":"212","text":"ad","css":"background-color: rgba(0,0,0,.55); color: #ffffff; border-color: #ffffff;"},"213":{"id":"213","text":"Ad","css":"background-color: #ffffff; color: #BC0000; border-color: #BC0000;"},"218":{"id":"218","text":"Ad","css":"background-color: rgba(0,0,0,.55); color: #00CC00; border-color: #a1a1a1;"},"241":{"id":"241","text":"AD","css":"background-color: #ffffff; color: #000000; border-color: #a1a1a1;"},"250":{"id":"250","text":"Ad","css":"background-color: rgba(0,0,0,.55); color: #ffffff; border-color: #ffffff;"},"263":{"id":"263","text":"Ad","css":"background-color: #ffffff; color: #000000; border-color: #000000;"},"265":{"id":"265","text":"AD","css":"background-color: #ffffff; color: #B250FF; border-color: #B250FF;"},"267":{"id":"267","text":"AD","css":"background-color: #ffffff; color: #BC0000; border-color: #BC0000;"},"272":{"id":"272","text":"AD","css":"background-color: #ffffff; color: #FF8514; border-color: #FF8514;"},"278":{"id":"278","text":"Ad","css":"background-color: #ffffff; color: #0071BC; border-color: #0071BC;"},"292":{"id":"292","text":"AD","css":"background-color: #ffffff; color: #009821; border-color: #009821;"},"310":{"id":"310","text":"AD","css":"background-color: #ffffff; color: #19b2b5; border-color: #19b2b5;"}}},"logUrls":{"og":"https:\/\/l3.aaxads.com\/log","pog":"https:\/\/p.aaxads.com\/log","aaxdbg":"___stu13p=aveoaamactga5dnnuee25racpo4cuud1vi7rv","axadc":"___stu13p=e4zfzmng4i7g13pbam2t4pz"},"aq":{"aqAdxEnd":"https:\/\/c.aaxads.com\/ssapi\/aqst","aqPubAdx":0,"aqlid":[]}};
'use strict';(function(){function a(a){return typeof a==="function"}function b(b,e,c){if(a(e)){c=e;e=[]}if(b===void 0||b===""||b===null||Object.prototype.toString.call(e)!=="[object Array]"||!a(c))return false;l[b]=l[b]||{gF:e,callback:c}}function e(b,g){var c=[],d;for(d in b)if(b.hasOwnProperty(d)){var q=b[d];if(typeof q==="object"||typeof q==="undefined")c.push(q);else{k[q]===void 0&&(k[q]=e(l[q].gF,l[q].callback));c.push(k[q])}}return a(g)?g.apply(this,c):c}var k={},l={};var g=typeof global!==
"undefined"&&typeof module==="object"?global:window;g.__ar=g.__ar||e;g.__ad=g.__ad||b})();
'use strict';__ad("_",["pqus","uhv",window,document,{}],function(a,b,e,k){function l(a,b,c){b="evt_"+(b||"gbl");Z[b]=Z[b]||{};Z[b][a]=Z[b][a]||[];Z[b][a].push(c)}function g(a){if(p(a)){var b="evt_"+a;p(Z[b])&&!q(Z[b])&&ba(Z[b],function(a,c){Z[b][c]=[]})}}function d(b,c,d,e){e=e||(typeof d==="object"?d:{});d=typeof d==="boolean"?d:false;var f="evt_"+(c||"gbl");if(Z[f]!==void 0){var g=Z[f][b]||[],k={src:c};Z.evt_gbl&&Z.evt_gbl.gblEvt&&a.ca(Z.evt_gbl.gblEvt[0],k,e);var l=0;for(c=g.length;l<c;l++)h(g[l])&&
a.ca(g[l],k,e);!d&&g.length>0&&(Z[f][b]=[])}}function n(a){try{a=a.frameElement}catch(H){return true}return false}function c(a,b){return p(a)?p(b)&&a.indexOf(b)!==-1:false}function r(a,b){return f(a)?W(a,function(a){if(a===b)return true})||false:false}function q(a){for(var b in a)if(a.hasOwnProperty(b))return false;return true}function p(a){switch(typeof a){case "string":return a!==void 0&&a!==""&&a!==null;case "object":return a!==null;case "number":case "boolean":return true;default:return false}}
function h(a){return typeof a==="function"}function f(a){return Object.prototype.toString.call(a)==="[object Array]"}function m(a){return p(a)?encodeURIComponent(a):""}function t(a){if(!p(a))return"";try{return decodeURIComponent(a)}catch(H){return a}}function u(a){if(!p(a))return{};var b={};var c=a.indexOf("?");if(c===-1)return b;a=a.substring(c+1).split("&");for(c=a.length;c--;){var d=a[c].split("=");b[d[0]]=d[1]}return b}function v(a){this.url=a;this.map=u(this.url)}function x(){var a=false;try{typeof e.top===
"object"&&typeof e==="object"&&(a=e.top!=e)}catch(H){a=true}return a}function w(a,b){a=Math.floor(Math.random()*(b-a+1)+a);a>b&&(a=b);return a}function y(a,b,c){c=c||null;b=b||[];return function(){var d=b.slice(0);arguments.length>0&&Array.prototype.push.apply(d,Array.prototype.slice.call(arguments));return a.apply(c,d)}}function z(a){try{var b=B(a);return[b&&(b.document||b)||false,b,null]}catch(ia){return[false,null,"Access Denied"]}}function B(a){try{return a.contentWindow||a.contentDocument}catch(H){return null}}
function A(a){var b;a=a.match(/^([1-9]\d*|0[0-7]*|0x[\da-f]+)(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?$/i);if(!a)return false;a[0]=0;for(b=1;b<5;b+=1){a[0]=a[0]+!!(a[b]||"").length;a[b]=parseInt(a[b],10)||0}a.push(256,256,256,256);a[4+a[0]]=a[4+a[0]]*Math.pow(256,4-a[0]);return a[1]>=a[5]||a[2]>=a[6]||a[3]>=a[7]||a[4]>=a[8]?false:a[1]*(a[0]===1||16777216)+a[2]*(a[0]<=2||65536)+a[3]*(a[0]<=3||256)+a[4]*1}function E(){return""+w(0,254)+
"."+w(0,254)+"."+w(0,254)+"."+w(0,254)}function C(a,b,c,d,e){c=c||R("@body:0");if(!c){Q("@body:0",100,y(C,[a,b,null,d,e]),false);return null}var f=(new G).set("marginWidth",0).set("marginHeight",0).set("scrolling","no").set("frameBorder",0).set("height",0).set("width",0).$n("display:none !important;").done();if(p(a))f.id=a;if(d)for(var g in d)f[g]=d[g];c.firstChild?c.insertBefore(f,c.firstChild):c.appendChild(f);b&&I(f,b);if(h(e))f.onload=e;return f}function I(b,c){if(b){var d=z(b),e;try{if(d[2]!==
null)throw d[2];if(e=d[0]){e.open();e.write(c);e.close()}}catch(na){d="javascript:var d=document.open();d.domain='"+k.domain+"';";b.src=d+"void(0);";try{var f=b.contentWindow.document;f.write(c);f.close()}catch(ta){b.src=d+'d.write("'+c.replace(/"/g,'\\"')+'");d.close();';a.na(ta)}}}}function K(a,b,c){if(!p(a))return"";p(c)&&p(c.encode)&&c.encode===true&&(b=m(b));return"&"+a+"="+b}function J(){return/msie|rv:11\.0/.test(da.toLowerCase())}function M(a){a=a.split("&");var b=[];ba(a,function(a){a.indexOf("=")!==
-1&&(a!==""&&a.substring(0,18)!=="action_object_map="&&a.substring(0,16)!=="action_type_map="&&a.substring(0,15)!=="action_ref_map="&&a.substring(0,18)!=="action_action_map="&&a.substring(0,3)!=="fb_"&&a.substring(0,6)!=="fbclid"&&a.substring(0,5)!=="lcid="&&a.substring(0,13)!=="force_hbtest="&&a.substring(0,10)!=="mnet_test="&&a.substring(0,12)!=="force_hbprv="&&a.substring(0,2)!=="a="&&a.substring(0,6)!=="kwp_0"&&a.substring(0,4)!=="utm_"&&a.substring(0,5)!=="code="&&a.substring(0,4)!=="bcmt"&&
b.push(a))});return b.join("&")}function O(){if(c(da,"Trident")||c(da,"MSIE")){var a=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(da);if(p(a)&&p(a[1]))return parseFloat(a[1])}return-1}function D(a,b){var c=/interactive|complete|loaded/;k.attachEvent&&O()<=10&&(c=/complete|loaded/);if(c.test(k.readyState))a();else{b||sa.V(e,"load",a);if(!b&&k.addEventListener)sa.V(k,"DOMContentLoaded",a);else if((b=k.documentElement)&&b.doScroll)try{b.doScroll("left");a()}catch(ja){setTimeout(y(D,[a,true]),50)}}}function G(a){this.frame=
a?a.document.createElement("iframe"):k.createElement("iframe")}function R(a){try{var b=a.charAt(0),c=a.substr(1).split(":"),d=c[0],e=p(c[1])&&parseInt(c[1],10);switch(b){case "@":var f=k.getElementsByTagName(d);break;case "#":f=k.getElementById(d);break;case "$":f=k.getElementsByName(d);break;case ".":f=P(k,d);break;default:f=k.getElementById(a)}return e===false?f:f[e]}catch(ta){return null}}function Q(a,b,c,d){try{var e=R(a),f=qa.mc().mn();e||!d&&f?c.call(null,e||false):setTimeout(y(Q,[a,b,c,d]),
b)}catch(ta){setTimeout(y(Q,[a,b,c,d]),b)}}function P(a,b,c){if(h(k.getElementsByClassName))return a.getElementsByClassName(b);c=c||"*";b=new RegExp("(^|\\s)"+b+"(\\s|$)");a=a||k;c=c==="*"&&a.all?a.all:a.getElementsByTagName(c);a=[];var d=c.length,e;for(e=0;e<d;e++){var f=c[e];b.test(f.className)&&a.push(f)}return a}function U(){return p(da)&&/ip(hone|od|ad)|android|blackberry|kindle|symbian|wap|windows (ce|phone)|palm( os)|iemobile|nokia|mobile/i.test(da)}function ea(){if(c(da,"Gecko")&&!c(da,"Trident")&&
!c(da,"MSIE")||c(da,"webkit"))return true;if(c(da,"Trident")||c(da,"MSIE")){var a=O();if(a>=11)return true}return false}function O(){if(c(da,"Trident")||c(da,"MSIE")){var a=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(da);if(p(a)&&p(a[1]))return parseFloat(a[1])}return-1}function V(a){var b=a.toString(),c=b.indexOf(".");return c!==-1?parseFloat(b.substr(0,Math.min(c+3,b.length))).toFixed(2):parseFloat(a).toFixed(2)}function Y(a){return p(a)?!isFinite(a)||isNaN(a)?0:a:0}function aa(){return e.location.href.indexOf("aax_test=")!==
-1}function ha(a,b){if(b===null||typeof b!=="object"||!p(a))return b;ba(b,function(b,c){a[c]=ha(a[c],b)});return a}function ba(a,b){if(p(a)){var c=0,d=a.length;if(f(a))for(;c<d;c++)b.call(a[c],a[c],c,d);else for(c in a)a.hasOwnProperty(c)&&b.call(a[c],a[c],c,0)}}function W(a,b){if(p(a)){h(b)||(b=function(a,b){return!!a});var c=0,d=a.length;if(f(a))for(;c<d;c++){var e=b.call(a[c],a[c],c);if(p(e))return e}else for(c in a)if(a.hasOwnProperty(c)){e=b.call(a[c],a[c],c);if(p(e))return e}}}function F(a,
b){if(!p(a))return[];var c;h(b)||(b=function(a,b){return!!a});var d=0,e=a.length;if(f(a))for(c=[];d<e;d++)c.push(b.call(a[d],a[d],d));else{c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=b.call(a[d],a[d],d))}return c}function L(a){return"CSS1Compat"==a.compatMode?a.documentElement:a.body}function X(a){if(p(a.innerHeight)&&p(a.innerWidth))return{width:a.innerWidth,height:a.innerHeight};var b=a.document,c=void 0,d=void 0;try{var e=L(b);if(!e){b.write('<div id="_mNTemp" style="display:none;"></div>');e=L(a.document);
var f=k.getElementById("_mNTemp");f.parentNode.removeChild(f)}if(e){c=e.clientWidth||void 0;d=e.clientHeight||void 0}}catch(ta){}return{width:c,height:d}}function la(){return!!(e.JSON&&(e.JSON.parse&&typeof JSON.parse==="function")&&(e.JSON.stringify&&typeof JSON.stringify==="function"))}function N(){return(new Date).getTime()}function T(a,b,c){c=c||"0";for(a+="";a.length<b;)a+=c;return a}function ka(){try{var a=k.cookie;return true}catch(H){return false}}function S(a,b){a=parseInt(a);return!isFinite(a)||
isNaN(a)?b:a}function ca(){return{CD:e.pageXOffset||e.scrollX,Br:e.pageYOffset||e.scrollY}}function Ha(a){return a===null||typeof a==="boolean"||typeof a==="number"||typeof a==="string"||typeof a==="symbol"||typeof a==="undefined"}function ma(a,b,c){ma.count=ma.count||0;ma.threshold=ma.threshold||c;setTimeout(function(){a.call(this);if(p(ma.threshold)){ma.count++;ma.count<ma.threshold&&ma(a,b,c)}else ma(a,b,c)},b)}function Ca(a,b){ba(b,function(b,c){Ha(b)||f(b)||!a.hasOwnProperty(c)?a[c]=b:a[c]=Ca(a[c],
b)});return a}function va(a){return W(a,function(a){if(a!==null&&typeof a==="object")return true})||false}function za(a){if(!p(a))return a;var b=f(a)?[]:{};if(!va(a)){ba(a,function(a,c){b[c]=a});return b}ba(a,function(a,c){if(f(a)){var d=va(a)?za(a):a.slice();b[c]=d}b[c]=a!==null&&typeof a==="object"?za(a):a});return b}function Da(a){if(la())return JSON.stringify(a);if(!p(a)||typeof a!=="object")return a===null?a+"":a;var b="";ba(a,function(c,d){if(c!==void 0){typeof c==="object"&&(c=Da(c));b=f(a)?
b+c:b+(d+":"+c);b+=","}});b=b.slice(0,b.length-1);return f(a)?"["+b+"]":"{"+b+"}"}function oa(){try{if("localStorage"in e&&e.localStorage!==null){e.localStorage.setItem("mntest","mntest");e.localStorage.removeItem("mntest");return la()}}catch(wa){}return false}function Ea(a,b){var c=0;F(a,function(a){b&&a[b]&&(c+=a[b])});return c}function pa(a){var b=R("@iframe");b=W(b,function(b){if(b.contentWindow===a)return b.id});return R("#"+b)}var Z={},da=navigator.userAgent,fa=Math.random(),sa={V:function(a,
b,c){a.addEventListener?a.addEventListener(b,c,false):a.attachEvent&&a.attachEvent("on"+b,c)},Ij:function(a,b,c){a.removeEventListener?a.removeEventListener(b,c):a.detachEvent&&a.detachEvent("on"+b,c)}};v.prototype.qH=function(a){return(a=this.map[a])&&t(a)||""};var qa=function(){function b(){function b(){for(d=true;e.length>0;){var a=e.shift();a.call(null)}e=[]}function c(){a.ca(b)}var e=[];this.md=function(a){e.push(a);e.length!==1||d?d&&c():D(c)};this.mn=function(){return d}}var c=null,d=false;
return{mc:function(){c===null&&(c=new b);return c}}}();G.prototype.set=function(a,b){this.frame[a]=b;return this};G.prototype.$n=function(a){this.frame.style.cssText=a;return this};G.prototype.done=function(){return this.frame};return{Jd:function ia(a){if(!ka())return null;var b=k.cookie.indexOf(a+"="),c=b+a.length+1;if(!b&&a!==k.cookie.substring(0,a.length)||b===-1)return null;a=k.cookie.indexOf(";",c);if(a===-1)a=k.cookie.length;return unescape(k.cookie.substring(c,a))},Pe:function ua(a,b,c,d,e,
f,h){if(ka()){var g=new Date;g.setTime(g.getTime());c&&(c*=864E5);h&&(c=h*6E4);h=new Date(g.getTime()+c);k.cookie=a+"="+escape(b)+(c?";expires="+h.toGMTString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(f?";secure":"")}},ao:T,O:m,$c:t,dw:function Aa(a){return t(a)!==a},qM:function na(a){var b=da.toLowerCase();return c(b,a)},yP:function ta(a){var b=a||"0123456789abcdefghijklmnopqrstuvwxyz";a=a.length;for(b=b.split("");a;){var c=Math.floor(Math.random()*a);a-=1;var d=b[a];b[a]=b[c];b[c]=d}return b.join("")},
gd:function Fa(a,b){if(!p(a)&&p(b))return null;return(a=(new RegExp("[?&]"+b+"=([^&#]*)","i")).exec(a))?a[1]:null},Ec:function Fa(a){a=t(a);return(a=a.match(/^http(?:s)?:\/\/([^/]+)/im))?a[1].toString():""},P:function Fa(){return p(e.location.href)?e.location.href:""},xh:function Ia(a){return typeof a==="string"},Yv:function Ka(a){return typeof a==="boolean"},K:function Ga(a){return p(a)},Gc:x(),Iia:x,ta:w,Ou:function Ma(a,b,c){c=Math.pow(10,c||2);return w(a*c,b*c)/c},kH:function Ba(){var a=new Date;
a=new Date(Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()));var b=new Date(Date.UTC(a.getUTCFullYear(),0,1));a.setUTCDate(a.getUTCDate()+4-(a.getUTCDay()||7));return Math.ceil(((a-b)/864E5+1)/7)},Mm:u,vA:v,DE:function Ma(a){return p(a)?a.search("^(http(s)?%253A%252F%252F)")!==-1?t(a):a.search("^(http(s)?://)")!==-1?m(a):a:""},X:sa,i:h,isArray:f,Uj:e.navigator.userAgent.toLowerCase(),wL:ea(),va:function Ja(a,b,c){var d={};if(p(c)&&p(c.encode))d.encode=c.encode;c="";var e,h=!!b,g=h?b:a,k;for(e in g)if(g.hasOwnProperty(e)){h&&
(e=b[e]);if(k=p(a[e])){k=a[e];k=typeof k!=="object"||k.tM!==false}if(k)if(f(a[e]))for(var l in a[e])c+=K(e+"[]",a[e][l],d);else{k=typeof a[e]==="object"?a[e].value:a[e];c+=K(e,k,d)}}return c},Ca:K,Kia:function lc(a){switch(typeof a){case "string":return p(a)&&(a==="1"||a==="true");case "number":return a!==0;case "boolean":return a;default:return false}},$:r,re:z,Wg:B,B:y,nk:G,Xc:Q,kc:P,Rv:A,JO:function Ja(a){var b=a.lastIndexOf(".");return b===-1?"":a.substr(0,b+1)+"0"},Rb:c,M:R,lf:function Xa(a,
b){a.firstChild?a.insertBefore(b,a.firstChild):a.appendChild(b)},jx:function Xa(a){a.parentNode.removeChild(a)},$e:I,Uia:function ub(a,b){I(a,'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; }};scriptElement.src = "'+
b+'"; tag.parentNode.insertBefore(scriptElement, tag);}\x3c/script></head><body onload="makeCall()"></body></html>')},Mja:function Za(a,b){if(a!==void 0&&b!==void 0&&a[b]!==void 0)return a[b]},Qc:qa,Jia:U,VL:function ub(){return p(da)&&/mac_powerpc|macintosh|mac\\sos|darwin\/|imac\/|macbookpro[\d]/i.test(da)},Ad:C,zh:function wb(b,c,d,e){if(p(b)){b.substr(0,4)!=="http"&&d===true&&(b=("https:"===k.location.protocol?"https:":"http:")+b);d=k.createElement("script");var f=k.getElementsByTagName("script")[0],
h=false;d.type="text/javascript";d.async=true;if(e&&e.crossOrigin)d.crossOrigin="anonymous";if(c&&typeof c==="function")d.onload=d.onreadystatechange=function(){if(!(h||this.readyState&&this.readyState!=="loaded"&&this.readyState!=="complete")){h=true;a.ca(c)}};d.src=b;f.parentNode.insertBefore(d,f)}},tj:function vb(a){if(p(a)){var b=k.createElement("script"),c=k.getElementsByTagName("script")[0];b.type="text/javascript";b.appendChild(k.createTextNode(a));c.parentNode.insertBefore(b,c)}},EM:function yb(a,
b,c){if(p(a)){a.substr(0,4)!=="http"&&(a=("https:"===k.location.protocol?"https:":"http:")+a);var d="aax_if"+c;l("prvreq",c,b);a=C(d,'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; window.parent.__ar([\'_\'], function(util){util.triggerEvent(\'prvreq\', "'+
c+'", false, window);});}};scriptElement.src = "'+a+'"; tag.parentNode.insertBefore(scriptElement, tag);}if(("performance" in window) && ("PerformanceObserver" in window)) {var observer = new PerformanceObserver(function (entries) {try {window.parent.aax.processPrefetchPerformanceEntries(entries.getEntries());} catch (e) {}});observer.observe({entryTypes: [\'resource\']});} \x3c/script></head><body onload="makeCall()"></body></html>');return z(a)[1]}},triggerEvent:d,ly:function $a(a,b,c,e){d("b:"+
a,b,c);d(a,b,c,e);d("a:"+a,b,c)},C:l,yia:function $a(a,b,c){var d=false;if(f(a)&&p(b)&&p(c)){ba(a,function(e,f,h){if((new RegExp(b)).test(e)===true){d=true;a[f]=c}});d===false&&a.push(c)}},pa:V,sf:function yb(){aa()&&(e.console&&e.console.log(Array.prototype.slice.call(arguments)))},Hn:aa,Pu:E,cha:function ab(a,b,c){var d=[],e,f=[],h={};if(a.length===0)return[""];if(p(c)&&p(c.encode))h.encode=c.encode;for(l in a[0])a[0].hasOwnProperty(l)&&d.push(l);var g="",k=J();var l=0;for(c=a.length;l<c;l++){var m=
"";var n=0;for(e=d.length;n<e;n++)m+=K(d[n]+"[]",a[l][d[n]],h);if(k&&p(b))if(m.length>b)f.push(m);else if((g+m).length>b){f.push(g);g=m}else g+=m;else g+=m}f.push(g);return f},Ji:function ab(a,b){var c="",d={};if(p(b)&&p(b.encode))d.encode=b.encode;ba(a,function(a,b){c+=K(b,a,d)});return c},u:function bb(a,b){a.fka=b;for(var c in b.prototype)a.prototype[c]=b.prototype[c];a.prototype.constructor=a},Cj:function qc(a,b){b*=6E4;return N()-a>b?false:true},D:new function bb(){var a={},b,c=false;this.startTime=
function(){return b};this.start=function(){b=(new Date).getTime();c=true};this.stop=function(){(new Date).getTime();c=false};this.dd=function(){return(new Date).getTime()-b};this.ia=function(b){a[b]={};a[b].startTime=c?this.dd():-1};this.qa=function(b){if(a.hasOwnProperty(b))a[b].endTime=a[b].startTime===-1?-1:this.dd()};this.time=function(b){if(a.hasOwnProperty(b)){a[b].endTime||this.qa(b);return a[b].endTime-a[b].startTime}return-1};this.getTime=function(b){return a.hasOwnProperty(b)?this.dd()-
a[b].startTime:-1}},extend:function Ra(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a},jo:ha,Hb:function zb(){try{return/loaded|complete/.test(k.readyState)}catch(Ra){return false}},Jha:function cb(a,b){b="evt_"+(b||"gbl");Z[b]&&Z[b][a]&&Z[b][a].length>0&&(Z[b][a]=[])},Fja:function Ab(){for(var a in Z)Z.hasOwnProperty(a)&&a.indexOf("evt_")!==-1&&(a.indexOf("cmd")===-1&&(Z[a]={}))},Gja:g,Hja:function cb(){g("gbl")},a:p,sL:function Bb(a){return typeof a!=="undefined"},trim:function Cb(a){return p(a)?
a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""):""},I:q,Ic:function Db(a){return typeof a==="object"&&a!==null&&!q(a)},hs:function Eb(a){if(!f(a))return{};for(var b=0,c=a.length,d={};b<c;b++)d[a[b]]=b+1;return d},map:F,reduce:function db(a,b,c){if(h(b)){if(f(a)){var d=0;var e=a.length;if(typeof c==="undefined"){for(;d<e&&!(d in a);)d++;if(d>=e)return;c=a[d++]}for(;d<e;d++)d in a&&(c=b(c,a[d],d,a));return c}c=c||"";for(d in a)a.hasOwnProperty(d)&&(c=b(c,a[d],d,a));return c}},filter:function db(a,
b){if(!p(a))return[];var c;h(b)||(b=function(a,b){return!!a});var d=0,e=a.length;if(f(a))for(c=[];d<e;d++)b.call(a[d],a[d],d)&&c.push(a[d]);else{c={};for(d in a)a.hasOwnProperty(d)&&(b.call(a[d],a[d],d)&&(c[d]=a[d]))}return c},Sb:function eb(a,b){b=b.split(".");var c;for(c=0;c<b.length;++c){if(a[b[c]]===void 0)return;a=a[b[c]]}return a},A:W,some:function fb(a,b){if(!p(a))return false;h(b)||(b=function(a,b){return!!a});var c=0,d=a.length;if(f(a))for(;c<d;c++){var e=b.call(a[c],a[c],c);if(e===true)return e}else for(c in a)if(a.hasOwnProperty(c)){e=
b.call(a[c],a[c],c);if(e===true)return e}return false},c:ba,ot:J,ye:X,Pg:function eb(){return X(e).width},nm:function fb(){return X(e).height},QJ:function Fb(){try{return e.screen.width+"x"+e.screen.height}catch(Gb){return""}},Ee:la,da:N,Ih:function gb(a,b){b=Math.pow(10,b);return Math.round(a*b)/b},cg:function gb(a){a=a||"";return a.replace(/\/$/,"")},ej:function Hb(a){if(h(Object.keys))return Object.keys(a);var b=[];ba(a,function(a,c){b.push(c)});return b},BI:function Ib(a){if(f(a)){a=Math.max.apply(null,
a);if(!isNaN(a))return a}},bja:function Jb(a,b){if(typeof a!=="object"||typeof b!=="string")return false;if(typeof a.className==="string")return(new RegExp("(^|\\s)"+b+"(\\s|$)")).test(a.className)},Vd:function Sa(a,b,c){var d=h(c)?c:Date.now,e=d();return function(){var c=d();if(c-e>=a){e=c;b.apply(null,arguments)}}},Oa:function Sa(a,b){if(a.style[b])return a.style[b];if(a.currentStyle)return a.currentStyle[b];if(k.defaultView&&k.defaultView.getComputedStyle){b=b.replace(/([A-Z])/g,"-$1");b=b.toLowerCase();
return(a=k.defaultView.getComputedStyle(a,""))&&a.getPropertyValue(b)}return null},$x:function Sa(a){if(p(a))a.style.cssText=(a.style.cssText||"")+";display:block!important;"},Dv:function hb(a){if(p(a))a.style.cssText=(a.style.cssText||"")+";display:none!important;"},Bg:function jb(c,d,f,h){var g=function(){},k=function(){(f.onload||g)(m.response||m.responseText)},l=function(){(f.onerror||g)()};if(!e.XMLHttpRequest){(f.Si||g)();return null}var m=new XMLHttpRequest,n=false;c=(c||b.Cz.D9).toUpperCase();
if("withCredentials"in m){m.open(c,d,true);m.withCredentials=p(f.withCredentials)?f.withCredentials:true}else if(e.XDomainRequest){m=new XDomainRequest;try{m.open(c,d)}catch(lb){(f.Si||g)();return null}}else{(f.Si||g)();return null}m.onload=m.onreadystatechange=function(){if(!n&&m.readyState==4){m.status==200?a.ca(k):l();n=true}};m.onerror=l;m.onabort=l;m.send(h);return true},nu:O,Om:function ib(a){var b;try{a&&a.data&&(typeof a.data==="string"&&la()&&(b=JSON.parse(a.data)))}catch(jb){}return b},
Nn:function ib(){return h(e.navigator.sendBeacon)?true:false},oL:function Kb(){return"withCredentials"in new XMLHttpRequest||typeof XDomainRequest!="undefined"?true:false},fI:function kb(a){function b(a){a=a.match(/\d+/g);return a===null||a.length===0?"":a[0]}a=a.frameElement;var c=String(a.height||"0"),d=String(a.width||"0");if(c.indexOf("%")!==-1||d.indexOf("%")!==-1){d=a.getBoundingClientRect&&a.getBoundingClientRect()||{};c=Math.ceil(d.height||a.clientHeight)||0;d=Math.ceil(d.width||a.clientWidth)||
0}else{c=b(c);d=b(d)}return d+"x"+c},fK:function kb(){try{var a=e.localStorage}catch(Ta){}if(p(a)){a=a.getItem("tpck");if(p(a))return a}return(e&&e.navigator&&e.navigator.cookieEnabled||navigator&&navigator.cookieEnabled)===false?0:""},$t:function Ta(a){a=R("#"+a);var b={},c=ca().CD,d=ca().Br,e={};p(a)&&h(a.getBoundingClientRect)&&(e=a.getBoundingClientRect());b.kka=S(e.top,0);b.Yga=S(e.bottom,0);b.Tia=S(e.left,0);b.Jja=S(e.right,0);b.top=S(e.top+d,0);b.bottom=S(e.bottom+d,0);b.left=S(e.left+c,0);
b.right=S(e.right+c,0);b.offsetX=S(c,0);b.offsetY=S(d,0);return b},Ka:function Ta(){var a=Array.prototype.slice.call(arguments),b=a[0];a.shift();ba(a,function(a){f(a)?Array.prototype.push.apply(b,a):b.push(a)});return b},Xa:S,Request:function Lb(a){var b={};this.input=function(a,c){b[a]=c;return this};this.get=function(a){return p(b[a])?b[a]:""};this.Hw=function(a){a&&(b=a);return this};this.freeze=function(){return b};this.deleteProperty=function(a){delete b[a]};a&&(b=a)},Ds:function lb(a){if(!p(a))return"";
var b=a.split("?")[0].split("#")[0];if(!p(b))return"";b=b.replace(/\/$/,"");var c=a.indexOf("#"),d="";c>0&&(d=a.substring(c+1));var e=a.indexOf("?");c=c>0?c:a.length;var f="";e>0&&(f=a.substring(e+1,c));a=M(f);p(a)&&(b=b+"?"+a);d=M(d);p(d)&&(b=b+"#"+d);return b},lN:function Mb(a,b){try{if(ea()){a.document.write(b);a.document.close()}else{a.hbContent="<!DOCTYPE html><html><head></head><body>"+b+"</body></html>";a.location.replace('javascript:window["hbContent"];')}return true}catch(Nb){return false}},
he:function mb(a,b,c){return(new G).set("marginWidth",0).set("marginHeight",0).set("scrolling","no").set("frameBorder",0).set("height",c||0).set("width",b||0).set("id",a).set("allowtransparency","true").done()},Kn:Ha,WD:function mb(a,b){p(b)||(b=0);return new Date(a.getTime()+b*6E4)},pN:ma,N:function Ob(b,c){return typeof b==="function"?y(a.ca,[c||null,b]):b},fj:function mb(){try{var a=e.document.body,b=e.document.documentElement;return Math.max(a.scrollHeight,a.offsetHeight,b.clientHeight,b.scrollHeight,
b.offsetHeight)}catch(Ua){return 0}},vh:n,ka:function Ob(){return T(A(E()),10)+""+w(1E6,9999999)+""+(new Date).getTime().toString()},Nb:function nb(a,b){return a*(1+b/100)},ux:Y,getFloatValue:function nb(a){a=Y(a);a=V(a);return parseFloat(a)},$w:Ca,Ps:za,Jb:function Pb(a){return p(a)&&(a<1||a*fa>1)},eh:function Pb(){return("https:"===e.location.protocol?"https:":"http:")+"//"+e.location.hostname},TM:Da,wl:function Qb(a){return a.substr(0,4)!=="http"?("https:"===k.location.protocol?"https:":"http:")+
a+a:a},XP:function Va(a,b){return a.length>b?a.substr(0,b):a},VI:ca,iK:function Va(a){for(var b=a.parent;b!==e.top;){a=a.parent;b=b.parent}return a},Wha:function Rb(a){(new Image).src=a},postMessage:function ob(a,b,c){var d=B(c);if(b&&p(d))if(e.postMessage&&h(d.postMessage))d.postMessage(a,"*");else if(b){if(typeof a==="object"){a=Da(a);a=escape(a)}b=b+"#"+k.location.href;c.src=b;d.location=b.replace(/#.*$/,"")+"#_CPM$"+a}},DL:function Sb(){return!!e.EventSource},We:oa,pj:function Dc(){return U()&&
!oa()},nJ:function pb(a,b){if(b){var c=Ea(a,b),d=w(0,100),e=0,f=null;if(c<1||c>100)return f;return f=W(a,function(a){if(a[b]){e+=a[b];if(d<e)return a}})}},vs:function Ub(a,b){return f(a)&&f(b)?W(a,function(a){return r(b,a)}):false},oK:function pb(){return e.navigator&&e.navigator.vendor},uh:function Ub(){if(navigator.userAgent.indexOf("CriOS")!==-1||navigator.userAgent.indexOf("FxiOS")!==-1)return false;var a=navigator.userAgent.toLowerCase(),b=navigator.vendor&&navigator.vendor.indexOf("Apple")>
-1||false;a=a.indexOf("safari")!==-1&&a.indexOf("chrome")===-1||false;return b||a},ZH:function Vb(a){var b=R("@head:0");if(b)return b.getAttribute(a)||""},CH:function Wb(a){return p(a)&&typeof a!=="undefined"?a.getAttribute("id")||a.id:""},Jj:function qb(a,b,c){return a.replace(new RegExp(b,"g"),c)},ym:function Xb(a){for(var b=e,c;b;){try{if(b.frames[a]){c=b;break}}catch(Yb){}if(b===e.top)break;b=b.parent}return c},RH:function qb(a){return n(a)?pa(a):a.frameElement}}});
'use strict';__ad("pqus",[window,document,{}],function(a,b){function e(a){typeof a.logLevel==="undefined"&&(a={logLevel:3,errorVal:a});a.logLevel>=3&&p[a.logLevel-1].push(a)}function k(a,b,c){this.name=a;this.message=b;this.logLevel=c}function l(){var a=Array.prototype.slice.call(arguments),b=a.length,c=null,d=null;if(typeof a[b-1]==="object"&&a[b-1]!==null&&a[b-1].constructor===k){var h=a[b-1];b--}if(typeof a[0]==="function"){var g=a.shift();b--}else{c=a.shift();g=a.shift();b-=2}a=a.slice(0,b);try{return g.apply(c,
a)}catch(w){if(h){w.name=h.name+" ("+w.name+")";w.message=h.message+" ("+w.message+")";d=h.logLevel}e({logLevel:d||3,errorVal:w});return new k}}function g(b,c){if(typeof b==="function")return a.setTimeout(function(){l(b)},c)}var d="",n="",c="",r,q=encodeURIComponent(navigator.userAgent),p=[];for(r=0;r<3;r++)p[r]=[];var h=function(){var c,e=0;for(c=0;c<3;c++)e+=p[c].length;if(e!==0){var k=new Image,l=(b.location.protocol==="https:"?"https":"http")+"://l3.aaxads.com/nerrping.php",r="",x=0;for(c=2;c>=
0;c--){for(e=p[c].length;0<e;){var w=c===1?p[c][0]:{logLevel:p[c][0].logLevel,errorVal:{name:p[c][0].errorVal.name,type:d,svr:n,message:p[c][0].errorVal.message,line:p[c][0].errorVal.lineNumber,description:p[c][0].errorVal.description,stack:p[c][0].errorVal.stack}};w=typeof JSON==="object"&&typeof JSON.stringify==="function"?JSON.stringify(w):void 0;if(w.length+r.length<=1200||!r.length){r.length!==0&&(r+=",");r+=w;p[c].shift();e--}else{x=1;break}}if(x)break}r=encodeURIComponent("["+r+"]");c=l+"?d="+
r+"&userAgent="+q+"&requrl="+encodeURIComponent(a.location.href)+"&img=logo.gif";k.src=c}g(h,2500)};a.addEventListener("load",h);return{ca:l,na:e,Th:function t(a){d=a},Cx:function u(a){n=a},Sx:function v(a){c=a},setTimeout:g}});
'use strict';__ad("qlf",["pqus",window,"_","uhv","performanceobserver"],function(a,b,e,k,l){function g(a){var b=e.extend({},q);return a=e.extend(b,a)}function d(b,c,d){c.kt===true&&(b=e.wl(b));e.a(c.js)&&e.c(c.js,function(a,b){f.setAttribute(b,a)});var f=document.createElement("script");c=document.getElementsByTagName("script")[0];var h=false;f.type="text/javascript";f.async=true;if(d&&typeof d==="function"){f.onload=f.onreadystatechange=function(){if(!(h||this.readyState&&this.readyState!=="loaded"&&
this.readyState!=="complete")){h=true;a.ca(d)}};f.onerror=function(){d.call(null,"error")}}f.src=b;c.parentNode.insertBefore(f,c)}function n(a,b){var c=new Image;a=e.XP(a,8E3);c.onload=b;c.src=a;c.onerror=function(){b.call(null,"error")}}function c(a,b){var c=new XMLHttpRequest,d=b.method==="POST"?a.url:a;if(!("withCredentials"in c)){c=new XDomainRequest;c.open(b.method,a);return c}c.open(b.method,d,true);c.withCredentials=e.a(b.withCredentials)?b.withCredentials:true;return c}function r(a,b,d){var e=
false,f=a.payload;try{var h=c(a,b)}catch(v){d.call(null,500,"error")}h.onload=h.onreadystatechange=function(){if(!e&&this.readyState===4){e=true;return this.status===200?d.call(null,null,this.response||this.responseText):d.call(null,this.state,"error")}};h.send(f)}var q={Y:["plvf"],method:"GET",type:"img",kt:false};return{submit:function t(a,c,k){e.isArray(a)||(a=[a]);c=g(c);k=k||function(){};e.c(a,function(a){var f=l.B(a,c,k);switch(c.type){case "img":n(a,f);break;case "script":d(a,c,f);break;case "xhr":r(a,
c,f);break;case "sb":f=c;if(e.Nn()){a=b.navigator.sendBeacon(a.url,a.payload)===false?"error":"success";l.Xr(f,a)}break;case "ifScr":var h=c;a=e.wl(a);e.C("prvreq",h.name,f);f=e.Ad("",'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; window.parent.__ar([\'_\'], function(util){util.triggerEvent(\'prvreq\', "'+
h.name+'", false, window);});}};scriptElement.src = "'+a+'"; tag.parentNode.insertBefore(scriptElement, tag);}if(("performance" in window) && ("PerformanceObserver" in window)) {var observer = new PerformanceObserver(function (entries) {try {window.parent.aax.processPrefetchPerformanceEntries(entries.getEntries());} catch (e) {}});observer.observe({entryTypes: [\'resource\']});} \x3c/script></head><body onload="makeCall()"></body></html>');e.re(f)}})},stream:function u(a,c,d){d=d||function(){};c=
g(c);var e=l.B(a,c,d);try{var f=new b.EventSource(a,{withCredentials:true})}catch(w){e.call(null,"error")}if(typeof f!=="undefined"){f.onopen=e;f.onerror=function(){e.call(null,"error")}}return f}}});
'use strict';__ad("performanceobserver",function(){return{B:function l(b,e,k){return k},Xr:function l(e,k){}}});
'use strict';__ad("srvwpf",function(){return{F:{},ce:{},af:{}}});
'use strict';__ad("ff",function(){return{PROVIDER_IDS:{},tp:{},kA:{},yA:{},Da:{},fA:{},zk:{},GC:{},cf:{},IB:{}}});
'use strict';__ad("ef",function(){return{tk:{},fg:{},hi:{},F:{},Nk:{},Pk:{},ef:{},be:{},ce:{}}});
'use strict';__ad("of",function(){return{xi:{},Pp:{},Gq:{},Pq:{},Mk:{},My:{},Ab:{},fg:{},Bk:{},Mz:{},xD:{},yi:{},eC:{},af:{},Ck:{},ef:{}}});
'use strict';__ad("postdataconstants",function(){return{F:{}}});
'use strict';__ad("uhv",function(){return{Event:{},Bz:{},cA:{},DB:{},uD:{},ez:{},Az:{},zk:{},af:{},mD:{}}});
'use strict';__ad("aqserviceconstants",function(){return{Request:{},Response:{}}});
'use strict';__ad("aaxframelogmanager",[window.aaxSettings,"_","of","uhv","inmemdatasource","qlf","adclog"],function(a,b,e,k,l,g,d){return{Kga:function r(c){var d={};d.hyw=c;d.flg=a.pub;d.jgsu=l.get("gdpr")?"1":"0";c=a.logUrls&&a.logUrls.og;var e=a.logUrls&&a.logUrls.aaxdbg;(new Image).src=c+"?"+e+b.va(d)},Cr:function p(e,k){var h=a.logUrls&&a.logUrls.pog,f=a.logUrls&&a.logUrls.axadc,m=l.get("aid"),q=l.for(m).get("acrid"),r=l.for(m).get("iurl");m=l.for(m).get("lid");e=d.uI(e,k,q,r,m);f+=b.va(e);g.submit({url:h,
payload:f},{method:"POST",Y:["orj"],type:"sb"})}}});
'use strict';__ad("inmemdatasource",["_","uhv"],function(a,b){function e(){var b={};this.set=function(d,c){a.a(d)&&a.Kn(d)&&(b[d]=c);return this};this.get=function(a){return b[a]||""}}function k(b){if(!a.a(b)||!a.Kn(b))return null;b=b.toString();a.a(l[b])||(l[b]=new e);return l[b]}var l={},g={};return{set:function r(a,b){return k("primary_in_mem_resource").set(a,b)},get:function r(a){return k("primary_in_mem_resource").get(a)},gP:function p(a,b){g[a]=b},mh:function p(a){g[a]||(g[a]=[]);return g[a]},
for:k}});
'use strict';__ad("ie",["feedbackuimanager","_","srvwpf","postdata","ff","uhv","inmemdatasource"],function(a,b,e,k,l,g,d){function n(){var a={};this.input=function(c,d){var f=/[$]{([A-Za-z_]+)}/g.exec(c);b.a(f)&&b.isArray(f)&&f[1]&&(c=f[1]);a[c]=d;return this};this.Gm=function(){return a}}function c(a,c){this.resolve=function(){return b.a(a)?a.replace(/[$]{([A-Za-z_]+)}/g,function(a,f){a=c[f];return b.a(a)?a:""}):""}}function r(a,c,d){if(!b.a(a)||!b.a(c)||!b.a(d))return true;var f=b.some(a.placements,
function(a){return a===c});b.a(a.placements)||(f=true);var e=b.some(a.providers,function(a){return a===d});b.a(a.providers)||(e=true);return f&&e&&b.a(a.enabled)?a.enabled:true}function q(a){a=(new k).set("type","feedback").set("aId",d.get("aid")).set("rate",a.Td).set("anim",a.reason&&a.reason.animated).set("ntRel",a.reason&&a.reason.notrelevant).set("prLb",a.reason&&a.reason.poorlylabeled).set("misL",a.reason&&a.reason.misleading).set("toob",a.reason&&a.reason.toobig);a.target(d.get("tarOg"));a.gb(d.get("fid"));
window.top.postMessage(a.Z(),a.target())}function p(b){function c(){q(e.Bt())}var d={Ig:3,Mx:true,Zc:{right:"0px",bottom:"0px"},Un:"//c.aaxads.com",Ah:"v2"},e=a(d,b);e.OP(function x(a){a>d.Ig&&q(e.Bt())});e.NP(c);e.MP(c);e.init();return e}return{sj:function t(a,d){var f=(b.a(a)?a:window).document,e='<span id="aax-ad-icon" class="advertisement-on-ad" ${ad_mark_block_css}>${ad_mark_block_text}</span>',g="AD",k="",m=(window.aaxSettings.feedbackConfig||{}).adIconConfig;if(b.a(d)&&b.a(m)){d=m[d];if(b.a(d)){b.a(d.text)&&
(g=d.text);b.a(d.css)&&(k='style="'+d.css+'"')}}d=new n;d.input("${ad_mark_block_text}",g).input("${ad_mark_block_css}",k);e=(new c(e,d.Gm())).resolve();e+='<div id="aax-feedback" class="container aax-popup hide"> <div class="popup-container"> <div class="logo-wrapper"> </div><div class="rating-block-wrapper"> <div class="aax-rating-block"> <div class="aax-rating hide"> <div class="aax-rating-text-wrapper"> <p class="aax-rating-text">We use user feedback to show better ads</p></div><div class="aax-stars-wrapper"> <p>Rate this Ad</p><ul class="star-list"> <li data-rate="5"></li><li data-rate="4"></li><li data-rate="3"></li><li data-rate="2"></li><li data-rate="1"></li></ul> </div></div><div class="aax-rating-feedback hide"> <ul class=""> <li> <label for="animated"> <input type="checkbox" name="animated" value="animated" id="animated"> <span class="checkmark"></span> Animated </label> </li><li> <label for="poorlylabeled"> <input type="checkbox" name="poorlylabeled" value="poorlylabeled" id="poorlylabeled"> <span class="checkmark"></span> Poorly Labeled </label> </li></ul> <ul class=""> <li> <label for="toobig"> <input type="checkbox" name="toobig" value="toobig" id="toobig"> <span class="checkmark"></span> Too Big </label> </li><li> <label for="notrelevant"> <input type="checkbox" name="notrelevant" value="notrelevant" id="notrelevant"> <span class="checkmark"></span> Not Relevant </label> </li></ul> <ul class="last-column"> <li> <label for="misleading"> <input type="checkbox" name="misleading" value="misleading" id="misleading"> <span class="checkmark"></span> Misleading Ad </label> </li></ul> <span class="submit"> <button type="button" name="button">Submit</button> </span> </div><div class="aax-rating aax-rating-last hide"> <p> <i></i> <span>Thanks for submitting the feedback</span> </p></div></div></div><p class="aax-optout hide"> Cookies help us deliver our services better. Click here to <a href="https://optout.aaxads.com" target="_blank">Opt Out</a>. </p></div><span class="close-feedback"> <i></i> </span></div><span id="aax-feedback-icon" class="feedback-cta"> <i></i> </span>';
g=f.createElement("div");for(g.innerHTML=e;g.firstChild;)f.body.appendChild(g.firstChild);return p(a)},Kr:function t(a){a=(b.a(a)?a:window).document;var c=a.createElement("link");c.rel="stylesheet";c.type="text/css";c.href="//c.aaxads.com/aax-style.css?ver=v2";a.getElementsByTagName("head")[0].appendChild(c)},vl:function v(a,c){a=parseInt(a,10);c=parseInt(c,10);var d=b.M("#aax-ad-icon"),e=b.M("#aax-feedback-icon"),g=c,k=window.aaxSettings.feedbackConfig||{};c=r(k.adIcon,a,g);a=r(k.fdIcon,a,g);c?b.$x(d):
b.Dv(d);a?b.$x(e):b.Dv(e)}}});
'use strict';__ad("feedbackuimanager",function(){return function(a,b){a=a?a:{};if(b&&b.document){var e=b.document,k={top:"auto",right:"auto",bottom:"auto",left:"auto"},l={pb:"#aax-feedback",Ig:3,Cg:".feedback-cta",ep:null,cp:null,Mx:false,Zc:null,Un:"images",Ah:null},g={},d={Td:null,reason:{}},n=[],c=[],r=[],q={},p=".loader",h=false,f=function(b,c,f){var d=e.querySelector(a.pb+" .logo-wrapper"),h=e.createElement("PICTURE"),g=e.createElement("SOURCE");g.srcset=a.Un+"/"+c+(a.Ah===null?"":"?ver="+a.Ah);
g.type="image/svg+xml";c=e.createElement("IMG");c.src=a.Un+"/"+f+(a.Ah===null?"":"?ver="+a.Ah);c.alt="AAX";c.className=b==="portrait"?"logo logo-portrait":b==="small"?"logo":"logo logo-standard";d.appendChild(h);h.appendChild(g);h.appendChild(c)},m={i:function(a){return{}.toString.call(a)==="[object Function]"},Gi:function(a,b,c){a.addEventListener?a.addEventListener(b,c,false):a.attachEvent&&a.attachEvent("on"+b,c)},CK:function(a,b){return-1<a.className.indexOf(b)},ee:function(a,b){if(!m.CK(a,b)){var c=
a.className.split(" ");c.push(b);a.className=c.join(" ")}return a},qd:function(a,b){a.className=a.className.replace(b,"").replace(/\s{2,}/g," ").replace(/^\s\s*/,"").replace(/\s\s*$/,"");return a},em:function(a){var b=[];a=e.querySelectorAll(a+" input");for(var c=0;c<a.length;c++)a[c].checked&&b.push(a[c]);return b},LO:function(){var c="",d=e.querySelector(a.pb),h=e.documentElement,g=e.getElementsByTagName("body")[0],k=b.innerWidth||h.clientWidth||g.clientWidth;h=b.innerHeight||h.clientHeight||g.clientHeight;
m.qd(d,"portrait");m.qd(d,"landscape");m.qd(d,"standard");if(k<h)c="portrait";else if(k>=675)c="landscape";else if(k>=225)c="standard";else if(k>=150&&h<150){c="small";m.fP()}c==="portrait"&&h<360?c="basic-small portrait":c==="landscape"&&h<90?c="basic-small horizontal":c==="standard"&&h<220&&(c="basic-small horizontal");c==="small"?f("small","logo-small.svg","logo-small.png"):c.indexOf("portrait")>-1?f("portrait","logo-small.svg","logo-small.png"):f("landscape","logo-horizontal.svg","logo-horizontal.png");
m.ee(d,c)},sO:function(){for(var b in k)k.hasOwnProperty(b)&&(a.Zc.hasOwnProperty(b)||(a.Zc[b]=k[b]))},rO:function(){var b=e.querySelector(a.Cg);b.style.top=a.Zc.top;b.style.right=a.Zc.right;b.style.bottom=a.Zc.bottom;b.style.left=a.Zc.left},fP:function(){a.Ig=0;g.Ig=0}},t={ZO:function(b){d.Td=(b.target||b.srcElement).getAttribute("data-rate");for(b=0;b<n.length;b++)n[b].call(q,d.Td);d.Td<=a.Ig?t.show(".aax-rating-feedback"):t.show(".aax-rating-last")},AO:function(b){b=m.em(a.pb+" .aax-rating-feedback");
for(var f=0;f<b.length;f++){d.reason[b[f].value]=1;b[f].checked=false}for(b=0;b<c.length;b++)c[b].call(q,d.Td,d.reason);t.show(".aax-rating-last")},pO:function(){if(!h&&d.Td!==null){for(var b=m.em(a.pb+" .aax-rating-feedback"),c=0;c<b.length;c++){d.reason[b[c].value]=1;b[c].checked=false}for(b=0;b<r.length;b++)r[b].call(q,d.Td,d.reason)}},show:function(b){h=b===".aax-rating-last";for(var c=e.querySelector(a.pb+" "+b),f=e.querySelector(".aax-popup"),d=e.querySelectorAll(".show"),g=0;g<d.length;g++)if(d[g]!==
f){m.qd(d[g],"show");m.ee(d[g],"hide")}c.className.indexOf("hide")>-1&&m.qd(c,"hide");m.ee(c,"show");c=e.querySelector(a.pb+" .aax-optout");if(b===".aax-rating"){m.qd(c,"hide");m.ee(c,"show")}else{m.qd(c,"show");m.ee(c,"hide")}},by:function(){var b=e.querySelector(a.pb+".aax-popup");b.className.indexOf("hide")>-1&&m.qd(b,"hide");m.ee(b,"show");h||t.ox()},Ev:function(){var b=e.querySelector(a.pb+".aax-popup");b.className.indexOf("show")>-1&&m.qd(b,"show");m.ee(b,"hide")},ox:function(){t.show(".aax-rating");
for(var b=m.em(a.pb+" .aax-rating-feedback"),c=0;c<b.length;c++)b[c].checked=false;d.Td=null;d.reason={}}},u=function(){for(var b=e.querySelectorAll(a.pb+" .star-list li"),c=0;c<b.length;c++)m.Gi(b[c],"click",t.ZO);m.Gi(e.querySelector(a.pb+" .aax-rating-feedback .submit button"),"click",t.AO);m.Gi(e.querySelector(a.Cg),"click",t.by);m.Gi(e.querySelector(a.pb+" .close-feedback"),"click",function(){t.pO();t.Ev()})};q.init=function(){a.Zc&&m.sO();for(var b in l)l.hasOwnProperty(b)&&(typeof a[b]==="undefined"&&
(a[b]=l[b]));for(var c in a)a.hasOwnProperty(c)&&(g[c]=a[c]);a.Zc&&m.rO();a.Mx&&m.LO();if(e.querySelector(a.pb)===null)throw"Container selector "+a.pb+" is not found/invalid";if(e.querySelector(a.Cg)===null)throw"CTA selector "+a.Cg+" is not found/invalid";if(a.cp||a.cp===0)e.querySelector(a.pb).style.zIndex=a.cp;if(a.ep||a.ep===0)e.querySelector(a.Cg).style.zIndex=a.ep;u();return q};q.Bt=function(){return d};q.OP=function(a){if(m.i(a)){n.push(a);return q}};q.NP=function(a){if(m.i(a)){c.push(a);return q}};
q.MP=function(a){if(m.i(a)){r.push(a);return q}};q.config=g;q.qx=t.ox;q.oja={show:t.by,on:t.Ev};return q}}});
'use strict';__ad("postdata",["_","postdataconstants"],function(a,b){function e(){var b={},e=this;this.get=function(a){return b[a]};this.set=function(a,e){b[a]=e;return this};this.Z=function(){return a.extend({},b)};this.Tb=function(d){b=a.extend({},d);return this};this.id=function(b){a.a(b)&&e.set("pid",b);return e.get("pid")};this.gb=function(b){a.a(b)&&e.set("pfid",b);return e.get("pfid")};this.target=function(b){a.a(b)&&e.set("ptarget",b);return e.get("ptarget")};this.source=function(b){if(a.a(b))e.set("psource",
b);else return e.get("psource")};e.set("pid",k++)}var k=1;e.F=b.F;return e});
'use strict';__ad("aq-request",[window.aaxSettings,"_","inmemdatasource","uhv","aqserviceconstants"],function(a,b,e,k,l){function g(a){if(typeof a==="undefined"||!a)throw"Invalid creative hash";var b={};b.crid=[a];a="";for(var d in b){if(!b.hasOwnProperty(d)||!b[d]||b[d].length<=0)return;var e="";b[d].forEach(function(a){e+="~"+a});a+="!"+d+e}if(!a.length)throw"Invalid creative hash string building";return a}var d=null;return{ZP:function q(c,e){if(!b.a(d)){var p=new b.Request;p.input("flg",a.pub).input("swulg",
a.pid).input("wbsh","media_aq").input("yhu",2).input("encryptionVersion","1.0").input("region","sc").input("gq",window.location.origin);d=p}c=e+g(c);d.input("elgghu_pds",c)},IJ:function r(){var a=window.aaxSettings.aq&&window.aaxSettings.aq.aqAdxEnd,e=b.a(d)?d.freeze():{};return!a||b.I(e)?"":a+"?"+b.va(e)}}});
'use strict';__ad("aq-service",[window.aaxSettings,"_","aq-request","aqserviceconstants","inmemdatasource","internal-winner-renderer","uhv"],function(a,b,e,k,l,g,d){function n(a,d,e,k){d=c(a,d);if(d.error){g.renderAd(a);h.Cd=4;k(h)}b.Bg("GET",d.url,{onload:function(c){c=JSON.parse(c);var f={Fe:false,error:null};try{if(!b.a(c)||!b.Ic(c)||b.I(c)||b.I(c.meta)||c.meta.status!=="SUCCESS")f.error="Invalid aq response for provider Id "+a+", aqResponse "+c;else{var d=l.get("aid"),m=c.status[a].crid,p=Object.keys(m)[0],
q=m[p].blocked,n=m[p].processed;l.for(d).set("aqb",q);l.for(d).set("aqp",n);l.for(d).set("acrid",p);f.Fe=!q}}catch(E){f.error="aq response read error"+E.message}if(f.error!==null){g.renderAd(a);h.Cd=3;k(h)}h.Fe=f.Fe;h.uw=f.uw;e(h)},onerror:function(b){g.renderAd(a);h.Cd=5;k(h)},Si:function(b){g.renderAd(a);h.Cd=6;k(h)}})}function c(a,b){var c={url:null,error:null};try{e.ZP(b,a);c.url=e.IJ()}catch(u){c.error="Error while build aq request and url, err "+u.bia()}return c}function r(a){var c={hash:null,
yM:false,error:null};try{var f=a.match(/https:\/\/tpc.googlesyndication.com.*?\/simgad\/[a-zA-Z0-9/_?&=]*/g),d=[],e=[];if(!b.a(f)||f.length===0){c.error="No sigmad found in Adcode";return c}f=f.filter(function(a,b,c){return c.indexOf(a)===b});b.c(f,function(a){var b=(new URL(a)).pathname.split("/");e.push(b[b.indexOf("simgad")+1]);d.push(a)});c.hash=q(e);p(f)}catch(x){c.error="Error while finding hash, err ="+x.message}return c}function q(a){a=a.sort().join();return btoa(a)}function p(a){var b=l.get("aid");
l.for(b).set("iurl",a||[])}var h={Fe:false,uw:false,pd:null,Cd:null};return{rN:function t(c){return new Promise(function(d,e){h.pd=a.gpvid;if(!b.a(c)){g.renderAd(h.pd);h.Cd=0;e(h)}var m=r(c.Gv);if(m.error!==null){g.renderAd(h.pd);h.Cd=1;e(h)}if(m.yM){h.Fe=true;h.Cd=2;d(h)}n(h.pd,m.hash,d,e)})}}});
'use strict';__ad("dfp-response-logger",["uhv","aq-service","aqserviceconstants","aaxframelogmanager","inmemdatasource","qlf","_"],function(a,b,e,k,l,g,d){function n(a){a.onload=function(a){if(!A){r(this,z,a);A=true}}}function c(a){a.onreadystatechange=function(b){if(!A){if(a.readyState===4&&a.status===200){r(this,z,b);A=true}u(this);t(this)}}}function r(a,b,c){q(a).then(function(a){b.call(this,c)})}function q(a){return new Promise(function(c,d){try{var e=f(a.responseText);if(e.length<1)c();else{var h=
e[0];y(h);w()&&x(e)?b.rN(h).then(function(b){l.for(l.get("aid")).get("aqp")||k.Cr(b,h);m(a,h,b.Fe);c(b)},function(b){l.for(l.get("aid")).get("aqp")||k.Cr(b,h);m(a,h,b.Fe);d("ads process error "+JSON.stringify(b))}):c(h)}}catch(M){p(M);d("adcode format and process error")}})}function p(a){g.submit({url:aaxSettings.logUrls&&aaxSettings.logUrls.pog,payload:h(a)},{method:"POST",Y:["orj"],type:"xhr",withCredentials:true})}function h(a){var b="&lwbsh=AAX&oyo=1";b+="&qdph=AD_CODE_FORMAT_ERROR&lwbsh="+a.message+
"&vwdfn="+encodeURIComponent(a.stack);return"___stu13p=1j1i1g49bxe3odqe1gncqvgbtbu1qf26wycb"+b}function f(a){for(var b=a.split("\n"),c=[],f=0;f<b.length;f++)if(f%2===0)if(!b[f]||f>=b.length-1)f++;else if(d.K(b[f])){var e=JSON.parse(b[f]);c.push({path:Object.keys(e)[0],config:e,Gv:b[f+1],raw:a})}return c}function m(a,b,c){var f=b.raw;if(!c){b.config[b.path][5]=0;b.config[b.path][6]=0;b.config[b.path][7]=0;f=JSON.stringify(b.config)+"\n"}v(a,f)}function t(a){a.__defineGetter__("onreadystatechange",
function(){return B});a.__defineSetter__("onreadystatechange",function(a){return B=a})}function u(a){a.__defineGetter__("onload",function(){return z});a.__defineSetter__("onload",function(a){return z=a})}function v(a,b){a.__defineGetter__("responseText",function(){return b});a.__defineGetter__("response",function(){return b})}function x(a){var b=true;a.length!==1&&(b=false);return b}function w(){var a=window.aaxSettings.aq.aqlid,b=l.for(l.get("aid")).get("lid");return b?a.includes(b):false}function y(a){var b=
a.config[a.path][15]&&a.config[a.path][15][0];if(!d.a(b)){p({message:"Line item id not present at the 15th index",stack:a.config[a.path]});return false}l.for(l.get("aid")).set("lid",b.toString())}var z=null,B=null,A=null;return{init:function C(){var a=window.XMLHttpRequest.prototype.open;window.XMLHttpRequest.prototype.open=function(b,f){if(f.indexOf("gampad/ads")!==-1){n(this);c(this)}a.apply(this,arguments)}}}});
'use strict';__ad("internal-winner-renderer",["_","pqus","inmemdatasource","qlf","uhv","ie","postdata","srvwpf"],function(a,b,e,k,l,g,d,n){function c(b,c){var h=document.getElementById("aax_standard");h.innerHTML="";b=a.he("aax_if_aax_standard",b,c);b.onload=function(){try{var b=window.__ar(["clickUrlExtractService"])[0]}catch(u){b=null}if(a.a(b)){var c=e.get("aid"),h=e.for(c).get("adCode");b=b.Wl(this.contentWindow,h);h=new d;h.set("aId",c).set("type","clickUrl").set("clickUrl",b||"");h.target(e.get("tarOg"));
h.gb(e.get("fid"));window.top.postMessage(h.Z(),h.target())}};h.appendChild(b);return b}var r=null;return{renderAd:function h(k){try{var f=null,m=e.get("aid"),p=e.for(m).get("szs")||"";a.a(p)&&p.length>0&&(f=p[0]);var n=e.for(m).get("adCode"),l=c(f[0],f[1]);var x=a.re(l)[1];a:{e.for(m).set("isAAX",true);e.for(m).set("iwraq","2");if(e.for(m).get("sRdOut")!=="1")try{x.document.open();x.document.write(n);x.document.close()}catch(I){b.na("Error while rendering the adcode");var w=false;break a}w=true}var y=
e.for(m).get("crid");p=w;n=!p;var z=e.for(m).get("sRdOut")==="1",B=e.for(m).get("aqp"),A=e.for(m).get("aqb"),E=e.for(m).get("iwraq"),C=(new d).set("aqp",B).set("aqb",A).set("status",p).set("type","renderad").set("isEmp",n?"1":"0").set("sz",f).set("isAaxWon",true).set("aId",m).set("iwr",E).set("sRdOut",z);C.target(e.get("tarOg"));C.gb(e.get("fid"));window.top.postMessage(C.Z(),C.target());r=g.sj(window,k);g.vl(y,k)}catch(I){throw"Internal renderAd exception, "+I.message;}}}});
'use strict';__ad("adclog",["_","of"],function(a,b){return{uI:function c(b,l,g,d,n){var k={hyw:"dadgf"};k.sylg=aaxSettings.gpvid||"";k.sfulg=encodeURIComponent(g);k.dgf=encodeURIComponent(l.Gv)||"";k.hv=b.Cd||"";b=a.a(d)&&d.length>0?encodeURIComponent(d.join("##")):"";k.lxuo=b||"";k.halg=aaxSettings.gexid||"";l=l.config[l.path];k.vc=l[6]+"x"+l[5]||"";k.olg=n||"";k.flg=aaxSettings.pub;k.lwbsh="AAX";return k}}});
'use strict';__ad("ddagif",["pqus","_","ff","qlf","srvwpf","ef","postdata","ie","uhv","inmemdatasource"],function(a,b,e,k,l,g,d,n,c,r){function q(a,c){var f=document.getElementById("aax_standard");f.innerHTML="";a=b.he("aax_if_aax_standard",a,c);a.onload=function(){try{var a=window.__ar(["clickUrlExtractService"])[0]}catch(w){a=null}if(b.a(a)){var c=r.get("aid"),f=r.for(c).get("adCode");a=a.Wl(this.contentWindow,f);f=new d;f.set("aId",c).set("type","clickUrl").set("clickUrl",a||"");f.target(r.get("tarOg"));
f.gb(r.get("fid"));window.top.postMessage(f.Z(),f.target())}};f.appendChild(a);return a}function p(c,e){var f=(new d).Tb(e.data),m=f.get("ac");c=f.get("lpx");var p=f.get("aId"),g=f.get("szs");e=f.get("crid");var l=f.get("pvid"),y=f.get("type")==="refReq";var z=f.get("pvid");f=f.get("aId");z==="207"?r.for(f).set("sRdOut","1"):r.for(f).set("sRdOut","0");r.set("aid",p);r.for(p).set("adCode",m);z=q(g[0][0],g[0][1]);z=b.re(z)[1];a:{r.for(p).set("isAAX",true);if(r.for(p).get("sRdOut")!=="1")try{z.document.open();
z.document.write(m);z.document.close()}catch(A){a.na("Error while rendering the adcode");m=false;break a}m=true}z=m;f=!z;var B=r.for(p).get("sRdOut")==="1";p=(new d).set("status",z).set("type","renderad").set("isEmp",f?"1":"0").set("sz",g[0].join("x")).set("isAaxWon",true).set("aId",p).set("sRdOut",B);p.target(r.get("tarOg"));p.gb(r.get("fid"));window.top.postMessage(p.Z(),p.target());y&&b.a(h)?h.qx():h=n.sj(window,l);n.vl(e,l);m&&c&&k.submit(c,{type:"img",Y:["win","plvf"]})}var h=null;return{init:function m(){b.C("aaxOnMes",
"gbl",p)}}});
'use strict';__ad("displayframecore",["_","pqus","uhv","postdata","ie","inmemdatasource","srvwpf","ddagif"],function(a,b,e,k,l,g,d,n){function c(){var a=(new k).set("phs",true);a.target(g.get("tarOg"));a.gb(g.get("fid"));window.top.postMessage(a.Z(),a.target())}function r(b){var c=window.document.createElement("div");c.id="aax_standard";a.Xc("@body:0",100,function(h){h.appendChild(c);a.i(b)&&b()})}b.Th("AAX");window.aax=window.aax||{};(function h(c){try{if(a.a(window.name)){var f=JSON.parse(window.name);
a.extend(c,f)}}catch(m){b.na("Failed to read window name")}a.c(c,function(a,b){g.set(b,a)})})(window.aax.__conf);g.set("gdpr",window.aaxSettings.gdpr==="1");g.set("gdprconsent",window.aaxSettings.gdprconsent);g.set("uspst",window.aaxSettings.uspst==="1");g.set("uspcn",window.aaxSettings.uspcn==="1");g.set("icr",window.aaxSettings.icr==="1");a.X.V(window,"message",a.N(function f(b){b.data&&b.origin===b.data.src&&b.data.id===a.Xa(g.get("fid"))&&(b.data.type==="initRen"||b.data.type==="refReq")&&a.triggerEvent("aaxOnMes",
"gbl",true,b)}));return{start:function f(){r(c);n.init();l.Kr(window)}}});window.__ar(["displayframecore"],function(a){a.start()});
} catch (err) {
    window.aax.err = err;
    window.aax.errConsts = {"name":"aaxDisplayIframe","type":"AAX_DISPLAY_IFRAME","svr":"2022012009_186","servname":"c8-web-25","message":"aaxDisplayIframe encountered an error","path":"\/nerrping.php","customerId":"AAXV53D7Q","hostName":"https:\/\/l3.aaxads.com","get":{"userAgent":"userAgent","requrl":"requrl","cid":"cid","img":"img","d":"d"}};'use strict';var ra=window.aax.err,xa=window.aax.errConsts;xa=xa||{};xa.get=xa.get||{};ra=ra||{};var ya={},Na="",Oa=encodeURIComponent(window.navigator.userAgent);Na=ra.stack?ra.stack:ra.s?ra.s:ra.stacktrace?ra.stacktrace:"No StackTrace";var Pa="",Qa;for(Qa in ra)ra.hasOwnProperty&&ra.hasOwnProperty(Qa)&&(Pa+=Qa+" : '"+ra[Qa]+"',");ya.logLevel=3;ya.errorVal={};ya.errorVal.name=xa.name;ya.errorVal.type=xa.type;ya.errorVal.svr=xa.svr;ya.errorVal.servname=xa.servname;ya.errorVal.message=xa.message;
ya.errorVal.stack=Na;ya.errorVal.objTrace=Pa;var sb="";sb=typeof JSON==="object"&&typeof JSON.stringify!=="undefined"?JSON.stringify(ya):ya.errorVal.name+"@#@"+ya.errorVal.type+"@#@"+Na+"@#@"+Pa;sb=encodeURIComponent("["+sb+"]");var tb=xa.hostName+xa.path+"?"+xa.get.userAgent+"="+Oa+"&"+xa.get.Eja+"="+encodeURIComponent(window.location.href)+"&"+xa.get.cid+"="+xa.customerId+"&"+xa.get.pia+"=logo.gif&"+xa.get.d+"="+sb;(new Image).src=tb;
};